<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6cc8b22dd640328ccde552ba63df306d
{
    public static $files = array (
        '2cffec82183ee1cea088009cef9a6fc3' => __DIR__ . '/..' . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SteemPHP\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SteemPHP\\' => 
        array (
            0 => __DIR__ . '/..' . '/davidkevork/steemphp/src/SteemPHP',
        ),
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'Michelf' => 
            array (
                0 => __DIR__ . '/..' . '/michelf/php-markdown',
            ),
        ),
        'J' => 
        array (
            'JsonRPC' => 
            array (
                0 => __DIR__ . '/..' . '/fguillot/json-rpc/src',
            ),
        ),
        'H' => 
        array (
            'HTMLPurifier' => 
            array (
                0 => __DIR__ . '/..' . '/ezyang/htmlpurifier/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6cc8b22dd640328ccde552ba63df306d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6cc8b22dd640328ccde552ba63df306d::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit6cc8b22dd640328ccde552ba63df306d::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
